name: test2-experimental

on:
  pull_request:
    paths-ignore:
      - 'waku/v1/**'
      - 'tests/all_tests_v1.nim'
      - 'tests/v1/**'

      - 'waku/whisper/**'
      - 'tests/whisper/**'
      - 'tests/all_tests_whisper.nim'
      
      - 'ci/**'
      - 'metrics/**'
      - 'docs/**'
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - 'ci/**'
      - 'metrics/**'
      - 'docs/**'
      - '**.md'

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  test:
    strategy:
      matrix:
        env:
          - NPROC: 2
            MAKEFLAGS: "-j${NPROC}"
            NIMFLAGS: "--parallelBuild:${NPROC}"
            # Add feature flags here
            RLN: "true"
            ONCHAIN_RLN: "true"
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    env: ${{ matrix.env }}
    timeout-minutes: 60

    name: ${{ github.workflow }}-${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        # We need to do this because of how github cache works
        # I am not sure we can move the cache file, so if we do not do this
        # make update breaks because the cached compiler is there where the submodules
        # are meant to go.
      - name: Submodules
        run: git submodule update --init --recursive

      - name: Cache nim
        uses: actions/cache@v3
        with:
          path: vendor/nimbus-build-system/vendor/Nim/bin
          key: ${{ runner.os }}-${{ matrix.env.NPROC }}-nim-${{ hashFiles('.gitmodules') }}

      - name: Update dependencies
        run: make V=1 update

      - name: Build V2 binaries
        run: make LOG_LEVEL=TRACE v2

      - name: Run V2 Tests
        run: make test2
